### ISSUE TITLE
Ažuriranje baze podataka

### ISSUE THREAD

**Issue by danielaL7** [AIR-FOI-HR/AIR1925#38]
Potrebno je ispraviti bazu podataka prema uputama sa konzultacija.
1. Ispraviti sva imenovanja na engleski jezik
2. Koristiti istu konvenciju imenovanja
3. Izbaciti atribut tip korisnika iz tablice korinsik te to izdovjiti u vanjsku tablicu
4. Izbaciti ENUM atribut iz tablice jela te to izbaciti u vanjsku tablicu kategorije
5. Svako jelo povezati sa korisnikom
6. Ispraviti dnevne menije prema dogovoru

**Comment by fmikolic** [comment]
Ispravljen ERA model aplikacija kako je dogovoreno na konzultacijama s mentorom. Molim provjeru.


![ERA_V3.png](https://images.zenhubusercontent.com/5dc0ba99eb486300018be585/24860acb-e1c1-4df3-b511-1427d5f4ed85)

**Comment by danielaL7** [comment]
Bilo bi dobro priložiti .sql file.

**Comment by fmikolic** [comment]
Ne mogu priložiti .sql file zbog toga što zenhub ne podržava taj tip datoteke. Spremljen je lokalno kod mene.

**Comment by danielaL7** [comment]
uredu, zatavramo task

**Comment by fmikolic** [comment]
![ERA_V4.png](https://images.zenhubusercontent.com/5dc0ba99eb486300018be585/1e981fce-01cd-4702-a471-06818b3932b3)

Ponovna provjera ERA modela, molim
