### ISSUE TITLE
Izradtiti xml ekran za popis menija

### ISSUE THREAD

**Issue by danielaL7** [AIR-FOI-HR/AIR1925#46]
Izraditi fragment na kojem bi trebao biti prikazan popis stavki menija.

Iznad se treba nalaziti padajući izbornik s popisom kategorija iz baze.

Klikom pojedine kategorije treba filtrirati ispod priloženi popis jela.

![image.png](https://images.zenhubusercontent.com/5dc0ba99eb486300018be585/73c5c653-be7f-40e1-9e15-c3075f35bc6e)

**Comment by fmikolic** [comment]
Molim provjeru odgovara li dizajn uvjetima zadanim na prototipu.
