### ISSUE TITLE
Izrada xml ekrana - Meni (restoran)

### ISSUE THREAD

**Issue by danielaL7** [AIR-FOI-HR/AIR1925#7]
forma za odabir kategorije.
Ispod toga lista menija, svaka stavka u lsiti treba imati oznaku delete i uredi.
Floating button za dodavanje stavke menija.
Material Design.
Prema prototipu.

![image.png](https://images.zenhubusercontent.com/5dc0ba99eb486300018be585/fb57a4c2-b3b5-4830-9d12-07db3548dbcd)

**Comment by fmikolic** [comment]
Molim provjeru odgovara li dizajn uvjetima zadanim na prototipu.
